services:
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    networks:
      - miner_network
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  pyasic-api:
    build: .
    container_name: pyasic-api
    ports:
      - "9000:9000"
    networks:
      - miner_network
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - NETWORK_PING_RETRIES=1
      - NETWORK_PING_TIMEOUT=3
      - NETWORK_SCAN_SEMAPHORE=
      - FACTORY_GET_RETRIES=1 
      - FACTORY_GET_TIMEOUT=3
      - GET_DATA_RETRIES=1
      - API_FUNCTION_TIMEOUT=5
      - ANTMINER_MINING_MODE_AS_STR=false
      - WHATSMINER_RPC_PASSWORD=admin
      - INNOSILICON_WEB_PASSWORD=admin
      - ANTMINER_WEB_PASSWORD=root
      - BOSMINER_WEB_PASSWORD=root
      - VNISH_WEB_PASSWORD=admin
      - GOLDSHELL_WEB_PASSWORD=123456789
      - AURADINE_WEB_PASSWORD=admin
      - EPIC_WEB_PASSWORD=letmein
      - HIVE_WEB_PASSWORD=admin
      - ANTMINER_SSH_PASSWORD=miner
      - BOSMINER_SSH_PASSWORD=root
      - SOCKET_LINGER_TIME=1000
      - SCAN_SUBNETS=10.66.10.0/24,192.168.1.0/24,10.0.0.0/24
      - SCAN_INTERVAL=300
      - REDIS_URL=redis://redis:6379

networks:
  miner_network:
    driver: bridge
